import TanstackProviders from "@/providers/TanstackProviders";
import "./globals.css";

export const metadata = {
  title: "Simple Post App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TanstackProviders>{children}</TanstackProviders>
      </body>
    </html>
  );
}
